# Generated by Django 3.1.1 on 2020-09-07 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cognome', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': ('Docente',),
                'verbose_name_plural': 'Docenti',
                'ordering': (['cognome', 'nome'],),
            },
        ),
        migrations.CreateModel(
            name='Esterno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('descrizione', models.TextField(max_length=100)),
            ],
            options={
                'verbose_name': ('Esterno',),
                'verbose_name_plural': 'Esterni',
                'ordering': (['nome'],),
            },
        ),
        migrations.CreateModel(
            name='FunzioneStrumentale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome della funzione strumentale', max_length=30, verbose_name='Funzione Strumentale')),
                ('descrizione', models.TextField(help_text='Descrizione della funzione strumentale', max_length=200, verbose_name='Descrizione FS')),
                ('docente_fs', models.ForeignKey(help_text='Docente incaricato per questa FS', on_delete=django.db.models.deletion.RESTRICT, to='progetti.docente', verbose_name='Docente')),
            ],
            options={
                'verbose_name': ('Funzione Strumentale',),
                'verbose_name_plural': 'Funzioni Strumentali',
                'ordering': (['nome'],),
            },
        ),
        migrations.CreateModel(
            name='Materiale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('descrizione', models.TextField(max_length=100)),
            ],
            options={
                'verbose_name': ('Materiale',),
                'verbose_name_plural': 'Materiali',
                'ordering': (['nome'],),
            },
        ),
        migrations.CreateModel(
            name='Progetto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(help_text='Titolo del progetto', max_length=50, verbose_name='Titolo Progetto')),
                ('obiettivi', models.TextField(help_text='Obiettivi del progetto', max_length=200)),
                ('n_docenti_dest', models.PositiveSmallIntegerField(help_text='Numero di docenti destinatari', verbose_name='Docenti destinatari')),
                ('n_studenti_dest', models.PositiveSmallIntegerField(help_text='Numero di studenti destinatari', verbose_name='Studenti destinatari')),
                ('n_esterni', models.PositiveSmallIntegerField(help_text='Numero di esterni coinvolti', verbose_name='Esterni coinvolti')),
                ('n_ore_previste', models.PositiveSmallIntegerField(help_text='Numero totale di ore previste', verbose_name='Ore previste')),
                ('doc_referente', models.ForeignKey(help_text='Docente responsabile del progetto', on_delete=django.db.models.deletion.RESTRICT, to='progetti.docente', verbose_name='Docente referente')),
                ('fs_referente', models.ForeignKey(help_text='Funzione stumentale referente del progetto', on_delete=django.db.models.deletion.RESTRICT, to='progetti.funzionestrumentale', verbose_name='FS referente')),
            ],
            options={
                'verbose_name': ('Progetto',),
                'verbose_name_plural': 'Progetti',
                'ordering': (['titolo'],),
            },
        ),
        migrations.CreateModel(
            name='UsoMateriale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materiale', models.ForeignKey(help_text='Il materiale in uso', on_delete=django.db.models.deletion.CASCADE, to='progetti.materiale', verbose_name='Materiale')),
                ('progetto', models.ForeignKey(help_text='Il progetto per il quale si usa questo materiale', on_delete=django.db.models.deletion.CASCADE, to='progetti.progetto', verbose_name='Progetto')),
            ],
            options={
                'verbose_name': ('Utilizzo',),
                'verbose_name_plural': 'Utilizzi',
                'ordering': (['progetto', 'materiale'],),
            },
        ),
    ]
