# Generated by Django 3.1.1 on 2020-09-07 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progetti', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progetto',
            options={},
        ),
    ]
