# Generated by Django 3.1.1 on 2020-10-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progetti', '0002_auto_20201026_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='progettazione',
            name='numeroOre',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='progettazione',
            name='tipoOre',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Ore retribuite'), (2, 'Ore in obbligo')], default=1),
        ),
        migrations.AlterField(
            model_name='realizzazione',
            name='tipoOre',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Docenza retribuita'), (2, 'Docenza in obbligo'), (3, 'Assistenza/Tutoraggio retribuita'), (4, 'Assistenza/Tutoraggio in obbligo')], default=1),
        ),
    ]
