# Generated by Django 3.1.1 on 2020-09-07 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progetti', '0002_auto_20200907_1252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progetto',
            options={'verbose_name': ('Progetto',), 'verbose_name_plural': 'Progetti'},
        ),
    ]
