# Generated by Django 3.1.1 on 2020-10-28 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('progetti', '0005_auto_20201027_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progettazione',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='info_progettazione_doc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='progettazione',
            name='progetto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='info_progettazione_prj', to='progetti.progetto'),
        ),
        migrations.AlterField(
            model_name='progetto',
            name='progettisti',
            field=models.ManyToManyField(related_name='prog_progettati', through='progetti.Progettazione', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='progetto',
            name='realizzatori',
            field=models.ManyToManyField(related_name='prog_realizzati', through='progetti.Realizzazione', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='realizzazione',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='info_realizzazione_doc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='realizzazione',
            name='progetto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='info_realizzazione_prj', to='progetti.progetto'),
        ),
    ]
