# Generated by Django 3.1.1 on 2020-10-14 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progetti', '0005_auto_20200908_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funzionestrumentale',
            name='nome',
            field=models.CharField(help_text='Nome della funzione strumentale', max_length=50, verbose_name='Funzione Strumentale'),
        ),
    ]
