# Generated by Django 3.1.1 on 2020-10-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progetti', '0006_auto_20201028_0821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progetto',
            name='n_ore_previste',
        ),
        migrations.AddField(
            model_name='progetto',
            name='stato_progetto',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Presentato'), (2, 'Approvato dalla Funzione strumentale'), (3, 'Approvato da DS / DSGA'), (4, 'Tutte le classi del triennio')], default=1, help_text="Situazione dell'approvazione del progetto", verbose_name='Stato del progetto'),
        ),
    ]
