# Generated by Django 3.1.1 on 2020-10-29 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progetti', '0007_auto_20201028_1009'),
        ('progetti', '0006_auto_20201028_1817'),
    ]

    operations = [
    ]
